### ISSUE TITLE
import MovieQA failed

### ISSUE THREAD

**Issue by DanlanChen** [makarandtapaswi/MovieQA_benchmark#1]
Hello, I wonder how to fix the bug that import MovieQA, no such module

**Comment by makarandtapaswi** [comment]
You need to add the folder in which you clone the repository to your <code>PYTHONPATH</code> environment variable, or <code>sys.path</code> inside the Python script.

For example if the folder is stored in <code>/foo/bar/MovieQA_benchmark</code>

the following should be added to the script
<code>import sys</code>
<code>sys.path.append('/foo/bar')</code>
<code>import MovieQA_benchmark as MovieQA</code>

**Comment by DanlanChen** [comment]
Fixed, Thank you
