### ISSUE TITLE
correct_index is null

### ISSUE THREAD

**Issue by DanlanChen** [makarandtapaswi/MovieQA_benchmark#2]
I saw in qa.json, the correct answer index is null sometimes. Could you exaplain why, should i just throw away this qa

**Comment by makarandtapaswi** [comment]
Those questions are from the test set for which you are supposed to predict the correct answer. We are preparing a server (should be ready by April 30) where you can upload the results on the test set, and we can let you know how well you perform.

You can train on the questions whose qid starts with "train:XX". The held-out test set can only be evaluated on the server ("test:XX"), but you can use the "val:XX" questions to test on your own.
