### ISSUE TITLE
Video clip name 

### ISSUE THREAD

**Issue by DanlanChen** [makarandtapaswi/MovieQA_benchmark#3]
Hello, I wonder what the name of the clip stands for, how could I match the clip back to the subtitles?

**Comment by makarandtapaswi** [comment]
The video clip field are the set of video files that may be used for answering. All sources use the imdb-key the ttXXXXXX to represent movies easily, and are linked with the question through the "imdb_key".

**Comment by JunweiLiang** [comment]
Do you have a script to align subtitle dialogs to the movie clip?

**Comment by JunweiLiang** [comment]
Do you use full movie subtitles for each question in the baseline paper?

**Comment by makarandtapaswi** [comment]
Hi,
In our baseline paper we used the full subtitles directly, and all clips provided for each movie. However, if you want to break it down, it can be done by using the frame-timestamp index and the video filenames. I don't have a script for this officially, but can make one in a few days.

For example, each video filename has the start and end frame number (from the complete movie),  `tt0109830.sf-010897.ef-013927.video.mp4` goes from frame number `10897` to `13927`. You can then translate the frame numbers to timestamps using the `story/video_meta/matidx/tt0109830.matidx` files, and crop out relevant parts of the subtitles using the timestamps.

Hope that helps
