### ISSUE TITLE
MovieQA Dataset Website Unavailable

### ISSUE THREAD

**Issue by QinghongLin** [makarandtapaswi/MovieQA_benchmark#4]
The movie video dataset website is currently unavailable, and we cannot access the videos. 

MovieQA is a very good dataset that has been released to the community, and we hope that it can continue to be available for use.

Best,
Kevin

**Comment by karttikeya** [comment]
Hi @makarandtapaswi,

Thank you for the amazing work and dataset. 

+1 to the question. Is the data no longer publicly available?

**Comment by makarandtapaswi** [comment]
Hi, Kevin's question was resolved. Karttikeya, please write to me on my email address makarand [dot] tapaswi [at] iiit [dot] ac [dot] in.

I'm closing this issue.
